stages:
  - lint
  - build

lint:
  image: python:3.10-alpine
  stage: lint
  before_script:
  - pip3 install pre-commit
  - apk add --no-cache bash git go
  - go install golang.org/x/tools/cmd/goimports@latest
  - export PATH="$HOME/go/bin:$PATH"
  script:
  - "pre-commit run -a"

build:
  image: dock.mau.dev/tulir/gomuks-build-docker:linux-amd64
  stage: build
  cache:
    paths:
    - .cache
  before_script:
  - apk add --no-cache git ca-certificates build-base su-exec olm-dev
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"
  - export GOCACHE="$CI_PROJECT_DIR/.cache/build"
  - export GO_LDFLAGS="-s -w -linkmode external -extldflags -static -X main.Tag=$CI_COMMIT_TAG -X main.Commit=$CI_COMMIT_SHA -X 'main.BuildTime=`date '+%b %_d %Y, %H:%M:%S'`'"
  script:
  - go build -ldflags "$GO_LDFLAGS" -o standupbot
  artifacts:
    paths:
    - standupbot
    - config.sample.json
